/// TASKS

### GET All Boards
GET http://localhost:4000/boards/9ac64d17-cd02-4e35-be95-a6680d52a41f/tasks HTTP/1.1

### GET Single Board
GET http://localhost:4000/boards/board_id_2/tasks/task_2_1_1 HTTP/1.1

### Create Board
POST http://localhost:4000/boards/board_id_2/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "create_task",
  "order": "100",
  "description": "string",
  "userId": "string",
  "columnId": "column_id_2_1"
}

### DELETE Board
DELETE  http://localhost:4000/boards/board_id_1/tasks/task_2 HTTP/1.1

### Update Board
PUT http://localhost:4000/boards/board_id_1/tasks/task_2 HTTP/1.1
Content-Type: application/json

{
  "title": "create_task",
  "order": "100",
  "description": "string",
  "userId": "string",
  "columnId": "column_id_1_1"
}
